name: trilhaapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  path_provider: ^2.1.1
  hive_generator: ^2.0.1
  sqflite: ^2.3.0
  dio: ^5.3.2
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.5.0
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  convex_bottom_bar: ^3.2.0
  brasil_fields: ^1.14.0
  intl: ^0.18.1
  battery_plus: ^4.0.2
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  assets:
    - lib/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"